### ISSUE TITLE
.gitignore file is breaking NPM build

### ISSUE THREAD

**Issue by sean-clayton** [VinSpee/react-container-query-container#4]
Me again! 😄 

By default, NPM uses a repo's `.gitignore` file if a `.npmignore` file does not exist. This project doesn't contain a `.npmignore` file, so `.gitignore` is used. Unfortunately, `.gitignore` ignores all the files necessary for successful NPM installs (`/lib`, specifically) 🙀 

Here is the current tree view of react-container-query-container:

```
react-container-query-container ❯❯❯ tree .
.
├── LICENSE
├── README.md
└── package.json

0 directories, 3 files
```

Suggested fix: Add a `.npmignore` that only ignores unnecessary files (.DS_Store, etc) and not the `/lib` folder like `.gitignore` does 👍

**Comment by VinSpee** [comment]
👍🏻 https://github.com/VinSpee/react-container-query-container/commit/c6f543b2525583b61faf509e70210d7b900ad11b

**Comment by sean-clayton** [comment]
@VinSpee is it possible to get an update out to NPM? Thanks, by the way, for looking into these things 😺
